title:              Zorgperfect. Zorg op maat

# Versioning
current_version: 0.1.0

author:
  name:             Jeffrey Overmeer
  email:            jeffrey.overmeer@gmail.com
  github:           jeffreyover
  twitter:          

# Dependencies
markdown:           kramdown
highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
source:             ./source
destination:        ./static

port:               3000
baseurl:            ""
url:

# exclude this stuff when building the static site
exclude:            ["sass","scss",".gitignore","README.md","config.codekit"]


## CUSTOM VARS

ga_id:              UA-46280099-1
site_name:          Zorgperfect
site_description:   Zorg op maat met een persoonlijke touch.
site_copyright:     © All Rights Reserved.
# site_url:           http://www.zorgperfect.nl

#local:
#site_url:           ""

# online:
site_url:           ""
site_email:         info@zorgperfect.nl
site_phone:         06 83 54 79 36



# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
